name: casla_production
description: Casla Group — Ứng dụng ghi nhận sản lượng sản xuất
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # State Management & DI
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: any

  # Database (Offline-first)
  drift: any
  drift_flutter: any
  sqlite3_flutter_libs: any

  # QR/Barcode Scanner
  mobile_scanner: any

  # Networking (SAP OData/RAP)
  dio: any

  # Immutable Models
  freezed_annotation: any
  json_annotation: any

  # Security
  flutter_secure_storage: any

  # Utilities
  uuid: any
  intl: any
  connectivity_plus: any
  device_info_plus: any
  logger: any
  package_info_plus: any

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

  # Code Generation
  build_runner: any
  freezed: any
  json_serializable: any
  riverpod_generator: any
  drift_dev: any
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_white.svg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/


#   fonts:
#     - family: Manrope
#       fonts:
#         - asset: assets/fonts/Manrope-Medium.ttf
#           weight: 500
#         - asset: assets/fonts/Manrope-Bold.ttf
#           weight: 700
#         - asset: assets/fonts/Manrope-ExtraBold.ttf
#           weight: 800
